name: Backend Commit Stage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            pact_url:
                description: 'URL of the pact file to verify'
                required: false

permissions:
    contents: write
    packages: write

env:
    AWS_ECR_ACCOUNT: 761018854156.dkr.ecr.ap-south-1.amazonaws.com
    AWS_REGION: ap-south-1

jobs:
    # Single job: install once, run all tests & static checks
    test_and_checks:
        name: Install, Tests & Static Checks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Compile Code (TypeScript)
              run: npm run build

            - name: Run Unit Tests
              run: npm run test:unit -- --coverage --watchAll=false

            - name: Run Provider Contract Verification (conditional)
              if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
              env:
                  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
                  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
                  GITHUB_SHA: ${{ github.sha }}
                  PACT_URL: ${{ github.event.inputs.pact_url }}
              run: npm run test:contract

            - name: Start Test Database
              run: docker compose up postgres -d

            - name: Wait for Test Database
              run: |
                  until docker compose exec postgres pg_isready -U code_clinic_user -d code_clinic_dev; do
                    echo "Waiting for test database..."
                    sleep 2
                  done

            - name: Setup Test Environment
              run: echo "DATABASE_URL=postgresql://code_clinic_user:dev_password@localhost:5432/code_clinic_dev" > .env

            - name: Run Narrow Integration Tests
              run: npm run test:integration

            - name: Stop Test Database
              if: always()
              run: docker compose down

            - name: Run Component Tests
              run: npm run test:component

            - name: Run Linting
              run: npm run lint

            - name: Run Static Code Analysis
              run: npm run lint:check

    # --- Parallel Docker job A: Backend -> GHCR ---
    docker_backend:
        name: Docker Build & Publish Backend Image
        runs-on: ubuntu-latest
        needs: [test_and_checks]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Docker CLI auth for GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Backend Image
              run: |
                  docker build -t code-clinic-backend:${{ github.sha }} .
                  docker tag code-clinic-backend:${{ github.sha }} code-clinic-backend:latest

            - name: Publish Backend Image to GHCR
              run: |
                  docker tag code-clinic-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/code-clinic-backend:${{ github.sha }}
                  docker tag code-clinic-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/code-clinic-backend:latest
                  docker push ghcr.io/${{ github.repository_owner }}/code-clinic-backend:${{ github.sha }}
                  docker push ghcr.io/${{ github.repository_owner }}/code-clinic-backend:latest

    # --- Parallel Docker job B: Lambda perform-examination -> ECR ---
    docker_lambda_perform_examination:
        name: Docker Build & Push Perform Examination Image
        runs-on: ubuntu-latest
        needs: [test_and_checks]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to AWS ECR
              run: |
                  aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_ACCOUNT }}

            - name: Build Lambda Image (perform-examination)
              run: |
                  docker build -t qa-code-clinic-perform-examination-processor:${{ github.sha }} -f Dockerfile.perform-examination.lambda .
                  docker tag qa-code-clinic-perform-examination-processor:${{ github.sha }} \
                    ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-perform-examination-processor:${{ github.sha }}
                  docker tag qa-code-clinic-perform-examination-processor:${{ github.sha }} \
                    ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-perform-examination-processor:latest

            - name: Push Lambda Image (perform-examination) to ECR
              run: |
                  docker push ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-perform-examination-processor:${{ github.sha }}
                  docker push ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-perform-examination-processor:latest

    # --- Parallel Docker job C: Lambda process-repository -> ECR ---
    docker_lambda_process_repository:
        name: Docker Build & Push Process Repository Image
        runs-on: ubuntu-latest
        needs: [test_and_checks]
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to AWS ECR
              run: |
                  aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_ACCOUNT }}

            - name: Build Lambda Image (process-repo)
              run: |
                  docker build -t qa-code-clinic-process-repository-processor:${{ github.sha }} -f Dockerfile.process-repo.lambda .
                  docker tag qa-code-clinic-process-repository-processor:${{ github.sha }} \
                    ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-process-repository-processor:${{ github.sha }}
                  docker tag qa-code-clinic-process-repository-processor:${{ github.sha }} \
                    ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-process-repository-processor:latest

            - name: Push Lambda Image (process-repo) to ECR
              run: |
                  docker push ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-process-repository-processor:${{ github.sha }}
                  docker push ${{ env.AWS_ECR_ACCOUNT }}/qa-code-clinic-process-repository-processor:latest
